2021-05-08 17:01:41,560 INFO    MainThread:45052 [wandb_setup.py:_flush():69] setting env: {}
2021-05-08 17:01:41,560 INFO    MainThread:45052 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-08 17:01:41,561 INFO    MainThread:45052 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\User\Documents\CS182\Project\CS182RLProject\wandb\run-20210508_170141-1bc66la5\logs\debug.log
2021-05-08 17:01:41,561 INFO    MainThread:45052 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\User\Documents\CS182\Project\CS182RLProject\wandb\run-20210508_170141-1bc66la5\logs\debug-internal.log
2021-05-08 17:01:41,562 INFO    MainThread:45052 [wandb_init.py:init():369] calling init triggers
2021-05-08 17:01:41,562 INFO    MainThread:45052 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-08 17:01:41,567 INFO    MainThread:45052 [wandb_init.py:init():418] starting backend
2021-05-08 17:01:41,567 INFO    MainThread:45052 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-05-08 17:01:41,575 INFO    MainThread:45052 [backend.py:ensure_launched():123] starting backend process...
2021-05-08 17:01:41,643 INFO    MainThread:45052 [backend.py:ensure_launched():128] started backend process with pid: 43096
2021-05-08 17:01:41,644 INFO    MainThread:45052 [wandb_init.py:init():423] backend started and connected
2021-05-08 17:01:41,645 INFO    MainThread:45052 [wandb_init.py:init():465] updated telemetry
2021-05-08 17:01:41,646 INFO    MainThread:45052 [wandb_init.py:init():484] communicating current version
2021-05-08 17:01:42,469 INFO    MainThread:45052 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-08 17:01:42,469 INFO    MainThread:45052 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-08 17:01:42,681 INFO    MainThread:45052 [wandb_init.py:init():522] starting run threads in backend
2021-05-08 17:01:42,724 INFO    MainThread:45052 [wandb_run.py:_console_start():1554] atexit reg
2021-05-08 17:01:42,725 INFO    MainThread:45052 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-08 17:01:42,725 INFO    MainThread:45052 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-08 17:01:42,725 INFO    MainThread:45052 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-08 17:01:42,726 INFO    MainThread:45052 [wandb_init.py:init():546] run started, returning control to user process
2021-05-08 17:01:42,735 INFO    MainThread:45052 [wandb_watch.py:watch():39] Watching
2021-05-08 17:01:42,743 INFO    MainThread:45052 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 1
2021-05-08 17:01:42,743 INFO    MainThread:45052 [wandb_run.py:_restore():1496] restore
2021-05-08 17:01:43,097 INFO    MainThread:45052 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 471
  total_bytes: 471
}

2021-05-08 17:01:43,728 INFO    MainThread:45052 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 471
  total_bytes: 1743
}

2021-05-08 17:01:44,029 INFO    MainThread:45052 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1745
  total_bytes: 1745
}

2021-05-08 17:01:44,140 INFO    MainThread:45052 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1745
  total_bytes: 1745
}

2021-05-08 17:01:44,246 INFO    MainThread:45052 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1745
  total_bytes: 1745
}

2021-05-08 17:01:44,360 INFO    MainThread:45052 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1745
  total_bytes: 1745
}

2021-05-08 17:01:44,467 INFO    MainThread:45052 [wandb_run.py:_wait_for_finish():1646] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1745
  total_bytes: 1745
}

2021-05-08 17:01:45,575 INFO    MainThread:45052 [wandb_run.py:_show_files():1868] logging synced files
